[[news]]
date = "2023-09"
content = "Beginning master study at Beijing University of Technology"

[[news]]
date = "2023-06"
content = "Research Intern at Soochow University, led by Prof. Lei Wang"

[[news]]
date = "2021-09"
content = "Joint training at Shenzhen Institute of Advanced Technology, led by Prof. Yong Zhang"

[[news]]
date = "2023-06"
content = "Highest-ranking graduation project in the entire school"
