type = "publication"
title = "Publications"
description = "A collection of my research work."
source = "publications.bib"

[pdfs]
wang2026largecall = "/LargeCall.pdf"
wang2025acccall = "/AccCall.pdf"
wang2024bp = "/bp.pdf"
wang2023ecg = "/ecg.pdf"
