[[news]]
date = "2026-08"
content = "进入北京航空航天大学攻读博士学位。"

[[news]]
date = "2026-05"
content = "论文 LargeCall 被 IEEE INFOCOM 2026 录用。"

[[news]]
date = "2025-09"
content = "论文 AccCall 发表于 ACM IMWUT（UbiComp 2025）。"

[[news]]
date = "2024-05"
content = "智能手机血压测量工作发表于 ACM IMWUT（UbiComp 2024）。"

[[news]]
date = "2023-09"
content = "用户无关的智能手机心电测量工作发表于 ACM IMWUT（UbiComp 2023）。"

[[news]]
date = "2023-09"
content = "进入北京工业大学攻读数学硕士学位。"

[[news]]
date = "2023-06"
content = "本科毕业设计获全学院最高排名。"

[[news]]
date = "2021-09"
content = "在张涌教授指导下于深圳先进技术研究院开展联合培养。"
